[tool.isort]
# Configuration for isort import sorting
profile = "django"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
known_django = "django"
known_first_party = "blowcomotion,search,website"
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "DJANGO", "FIRSTPARTY", "LOCALFOLDER"]
skip = ["migrations", "__pycache__", ".git", ".venv", "venv", "env"]
