# Generated by Django 5.1.6 on 2025-02-23 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0003_alter_sitesettings_facebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blankcanvaspage',
            name='body',
        ),
    ]
