# Generated by Django 5.1.6 on 2025-02-23 06:22

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0004_remove_blankcanvaspage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blankcanvaspage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 1), ('rich_text', 2)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.StructBlock', [[('image', 0)]], {}), 2: ('wagtail.blocks.RichTextBlock', (), {})}, null=True),
        ),
    ]
