# Generated by Django 5.1.6 on 2025-02-24 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0005_blankcanvaspage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, help_text="e.g. 'Mueller Lake Park, Austin, TX'", max_length=255, null=True)),
                ('location_url', models.URLField(blank=True, help_text='URL for a map of the location', null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
