# Generated by Django 5.1.6 on 2025-02-24 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0008_section_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blowcomotion.section'),
        ),
    ]
