# Generated by Django 5.1.6 on 2025-02-24 05:32

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0009_alter_instrument_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='instruments',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='+', to='blowcomotion.instrument'),
        ),
        migrations.AlterField(
            model_name='section',
            name='instructors',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, limit_choices_to={'instructor': True}, related_name='+', to='blowcomotion.member'),
        ),
        migrations.AlterField(
            model_name='section',
            name='members',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='+', to='blowcomotion.member'),
        ),
    ]
