# Generated by Django 5.1.6 on 2025-02-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0010_alter_member_instruments_alter_section_instructors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
