# Generated by Django 5.1.6 on 2025-02-24 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0011_instrument_sort_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='instruments',
        ),
        migrations.DeleteModel(
            name='Instrument',
        ),
    ]
