# Generated by Django 5.1.6 on 2025-02-24 06:07

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0014_remove_instrument_member_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blowcomotion.member')),
                ('section', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_instructors', to='blowcomotion.section')),
            ],
        ),
        migrations.CreateModel(
            name='SectionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blowcomotion.member')),
                ('section', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_members', to='blowcomotion.section')),
            ],
        ),
    ]
