# Generated by Django 5.1.6 on 2025-02-24 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0017_alter_sectioninstructor_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectioninstructor',
            old_name='member',
            new_name='instructor',
        ),
    ]
