# Generated by Django 5.1.6 on 2025-02-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0018_rename_member_sectioninstructor_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='instruments',
            field=models.ManyToManyField(blank=True, to='blowcomotion.instrument'),
        ),
        migrations.DeleteModel(
            name='MemberInstrument',
        ),
    ]
