# Generated by Django 5.1.6 on 2025-02-24 22:42

import django.db.models.deletion
import modelcluster.fields
import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0020_remove_member_instruments_memberinstrument'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('time_signature', models.CharField(max_length=255)),
                ('key_signature', models.CharField(max_length=255)),
                ('style', models.CharField(max_length=255)),
                ('composer', models.CharField(max_length=255)),
                ('arranger', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('music_video_url', models.URLField(blank=True, null=True)),
                ('conductors', models.ManyToManyField(blank=True, related_name='conducted_songs', to='blowcomotion.member')),
                ('event', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='setlist', to='blowcomotion.event')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, wagtail.search.index.Indexed),
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_part_uploaded', models.BooleanField(default=False)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blowcomotion.instrument')),
                ('pdf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document')),
                ('song', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='blowcomotion.song')),
            ],
        ),
    ]
