# Generated by Django 5.1.6 on 2025-02-24 22:45

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0022_alter_song_arranger_alter_song_composer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='conductors',
        ),
        migrations.CreateModel(
            name='SongConductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blowcomotion.member')),
                ('song', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='conductors', to='blowcomotion.song')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
