# Generated by Django 5.1.6 on 2025-02-24 22:47

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0023_remove_song_conductors_songconductor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='event',
        ),
        migrations.CreateModel(
            name='EventSetlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('event', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='setlist', to='blowcomotion.event')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blowcomotion.song')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
