# Generated by Django 5.1.6 on 2025-02-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0025_chart_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='part',
            field=models.CharField(blank=True, help_text=" e.g. '2nd Trombone' If left blank, instrument name will be used.", max_length=255, null=True),
        ),
    ]
