# Generated by Django 5.1.6 on 2025-02-26 05:43

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0028_alter_blankcanvaspage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_scroller_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blowcomotion.customimage'),
        ),
        migrations.AlterField(
            model_name='blankcanvaspage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 1), ('rich_text', 2), ('events', 6)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 1: ('wagtail.blocks.StructBlock', [[('image', 0)]], {}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {}), 4: ('blowcomotion.chooser_blocks.EventChooserBlock', (), {}), 5: ('wagtail.blocks.ListBlock', (4,), {}), 6: ('wagtail.blocks.StructBlock', [[('scroller_title', 3), ('events', 5)]], {})}, null=True),
        ),
    ]