# Generated by Django 5.1.6 on 2025-02-26 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0029_event_event_scroller_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_scroller_image',
            field=models.ForeignKey(blank=True, help_text='Image to be used in the event scroller component', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blowcomotion.customimage'),
        ),
    ]
