# Generated by Django 5.1.6 on 2025-03-12 05:19

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blowcomotion", "0030_alter_event_event_scroller_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blankcanvaspage",
            name="body",
            field=wagtail.fields.StreamField(
                [("hero", 1), ("rich_text", 2), ("events", 10)],
                blank=True,
                block_lookup={
                    0: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    1: ("wagtail.blocks.StructBlock", [[("image", 0)]], {}),
                    2: ("wagtail.blocks.RichTextBlock", (), {}),
                    3: ("wagtail.blocks.CharBlock", (), {}),
                    4: ("blowcomotion.chooser_blocks.GigoGigChooserBlock", (), {}),
                    5: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("details", 4), ("event_scroller_image", 5)]],
                        {},
                    ),
                    7: ("wagtail.blocks.ListBlock", (6,), {}),
                    8: ("blowcomotion.chooser_blocks.EventChooserBlock", (), {}),
                    9: (
                        "wagtail.blocks.ListBlock",
                        (8,),
                        {
                            "help_text": "Events that are not associated with Gig-o-Matic"
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("scroller_title", 3), ("gigo_gigs", 7), ("events", 9)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
