# Generated by Django 5.1.6 on 2025-03-21 04:43

import wagtail.fields
from django.db import migrations

import blowcomotion.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("blowcomotion", "0033_sitesettings_header_menus_alter_blankcanvaspage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="header_menus",
            field=wagtail.fields.StreamField(
                [("menu_item", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.PageChooserBlock", (), {}),
                    1: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    2: (
                        "wagtail.blocks.ListBlock",
                        (blowcomotion.blocks.MenuItemBlock,),
                        {"collapsed": True, "required": False},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 0), ("label", 1), ("submenus", 2)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
