# Generated by Django 5.1.6 on 2025-03-22 00:00

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blowcomotion", "0034_alter_sitesettings_header_menus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blankcanvaspage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("column_layout", 8),
                    ("events", 16),
                    ("hero", 18),
                    ("rich_text", 2),
                    ("upcoming_events", 19),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                            ]
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("rich_text", 0), ("align", 1)]],
                        {},
                    ),
                    3: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"template": "blocks/image_block.html"},
                    ),
                    4: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 2), ("image", 3)]],
                        {"required": False},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("left_column", 4), ("right_column", 4)]],
                        {},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("left_column", 4),
                                ("middle_column", 4),
                                ("right_column", 4),
                            ]
                        ],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("left_column", 4),
                                ("middle_column", 4),
                                ("right_column", 4),
                                ("middle_left_column", 4),
                                ("middle_right_column", 4),
                            ]
                        ],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.StreamBlock",
                        [[("two_column", 5), ("three_column", 6), ("four_column", 7)]],
                        {},
                    ),
                    9: ("wagtail.blocks.CharBlock", (), {}),
                    10: ("blowcomotion.chooser_blocks.GigoGigChooserBlock", (), {}),
                    11: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("details", 10), ("event_scroller_image", 11)]],
                        {},
                    ),
                    13: ("wagtail.blocks.ListBlock", (12,), {}),
                    14: ("blowcomotion.chooser_blocks.EventChooserBlock", (), {}),
                    15: (
                        "wagtail.blocks.ListBlock",
                        (14,),
                        {
                            "help_text": "Events that are not associated with Gig-o-Matic"
                        },
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("scroller_title", 9), ("gigo_gigs", 13), ("events", 15)]],
                        {},
                    ),
                    17: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    18: ("wagtail.blocks.StructBlock", [[("image", 17)]], {}),
                    19: ("blowcomotion.blocks.UpcomingPublicGigs", (), {}),
                },
                null=True,
            ),
        ),
    ]
