# Generated by Django 5.1.6 on 2025-04-03 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blowcomotion", "0038_alter_blankcanvaspage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="footer_text",
            field=models.CharField(
                blank=True,
                help_text="Text to display in the footer",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="instagram",
            field=models.URLField(blank=True, null=True),
        ),
    ]
