# Generated by Django 5.1.6 on 2025-04-06 21:13

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blowcomotion", "0041_alter_blankcanvaspage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blankcanvaspage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("column_layout", 8),
                    ("events", 16),
                    ("full_width_image", 18),
                    ("hero", 21),
                    ("multi_image_banner", 23),
                    ("quoted_image", 25),
                    ("rich_text", 2),
                    ("spacer", 26),
                    ("upcoming_events", 27),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                            ]
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("rich_text", 0), ("align", 1)]],
                        {},
                    ),
                    3: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"template": "blocks/image_block.html"},
                    ),
                    4: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 2), ("image", 3)]],
                        {"required": False},
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("left_column", 4), ("right_column", 4)]],
                        {},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("left_column", 4),
                                ("middle_column", 4),
                                ("right_column", 4),
                            ]
                        ],
                        {},
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("left_column", 4),
                                ("middle_column", 4),
                                ("right_column", 4),
                                ("middle_left_column", 4),
                                ("middle_right_column", 4),
                            ]
                        ],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.StreamBlock",
                        [[("two_column", 5), ("three_column", 6), ("four_column", 7)]],
                        {},
                    ),
                    9: ("wagtail.blocks.CharBlock", (), {}),
                    10: ("blowcomotion.chooser_blocks.GigoGigChooserBlock", (), {}),
                    11: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("details", 10), ("event_scroller_image", 11)]],
                        {},
                    ),
                    13: ("wagtail.blocks.ListBlock", (12,), {}),
                    14: ("blowcomotion.chooser_blocks.EventChooserBlock", (), {}),
                    15: (
                        "wagtail.blocks.ListBlock",
                        (14,),
                        {
                            "help_text": "Events that are not associated with Gig-o-Matic"
                        },
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("scroller_title", 9), ("gigo_gigs", 13), ("events", 15)]],
                        {},
                    ),
                    17: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    18: ("wagtail.blocks.StructBlock", [[("image", 17)]], {}),
                    19: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    20: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 17),
                                ("top_line", 19),
                                ("middle_line", 19),
                                ("bottom_line", 19),
                                ("youtube_url", 20),
                            ]
                        ],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.ListBlock",
                        (17,),
                        {
                            "help_text": "Select images to display in the banner.",
                            "max_num": 7,
                            "min_num": 7,
                        },
                    ),
                    23: ("wagtail.blocks.StructBlock", [[("images", 22)]], {}),
                    24: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 17),
                                ("header", 19),
                                ("subheader", 24),
                                ("author", 19),
                            ]
                        ],
                        {},
                    ),
                    26: ("blowcomotion.blocks.SpacerBlock", (), {}),
                    27: ("blowcomotion.blocks.UpcomingPublicGigs", (), {}),
                },
                null=True,
            ),
        ),
    ]
