# Generated by Django 5.1.6 on 2025-04-11 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blowcomotion", "0045_alter_blankcanvaspage_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="WikiIndexPage",
            fields=[
                (
                    "blankcanvaspage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="blowcomotion.blankcanvaspage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wiki Index Page",
                "verbose_name_plural": "Wiki Index Pages",
            },
            bases=("blowcomotion.blankcanvaspage",),
        ),
        migrations.CreateModel(
            name="WikiPage",
            fields=[
                (
                    "blankcanvaspage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="blowcomotion.blankcanvaspage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wiki Page",
                "verbose_name_plural": "Wiki Pages",
            },
            bases=("blowcomotion.blankcanvaspage",),
        ),
    ]
