# Generated by Django 5.1.6 on 2025-04-15 18:28

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blowcomotion", "0047_wikiauthor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blankcanvaspage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("column_layout", 10),
                    ("countdown", 18),
                    ("events", 25),
                    ("full_width_image", 27),
                    ("hero", 30),
                    ("horizontal_rule", 4),
                    ("multi_image_banner", 32),
                    ("quoted_image", 34),
                    ("rich_text", 2),
                    ("spacer", 5),
                    ("upcoming_events", 36),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                            ]
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("rich_text", 0), ("align", 1)]],
                        {},
                    ),
                    3: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"template": "blocks/image_block.html"},
                    ),
                    4: ("blowcomotion.blocks.HorizontalRuleBlock", (), {}),
                    5: ("blowcomotion.blocks.SpacerBlock", (), {}),
                    6: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("rich_text", 2),
                                ("image", 3),
                                ("horizontal_rule", 4),
                                ("spacer", 5),
                            ]
                        ],
                        {"required": False},
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("left_column", 6), ("right_column", 6)]],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("left_column", 6),
                                ("middle_column", 6),
                                ("right_column", 6),
                            ]
                        ],
                        {},
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("left_column", 6),
                                ("middle_column", 6),
                                ("right_column", 6),
                                ("middle_left_column", 6),
                                ("middle_right_column", 6),
                            ]
                        ],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.StreamBlock",
                        [[("two_column", 7), ("three_column", 8), ("four_column", 9)]],
                        {},
                    ),
                    11: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    12: (
                        "wagtail.blocks.DateBlock",
                        (),
                        {"help_text": "Enter the date for the countdown."},
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the top line text for the countdown.",
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the sub line text for the countdown.",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the text for the button.",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Enter the URL for the button.",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("_self", "Same Tab"), ("_blank", "New Tab")],
                            "help_text": "Select the target for the button.",
                        },
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_image", 11),
                                ("countdown_date", 12),
                                ("head_line", 13),
                                ("sub_line", 14),
                                ("button_text", 15),
                                ("button_url", 16),
                                ("button_target", 17),
                            ]
                        ],
                        {},
                    ),
                    19: ("wagtail.blocks.CharBlock", (), {}),
                    20: ("blowcomotion.chooser_blocks.GigoGigChooserBlock", (), {}),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [[("details", 20), ("event_scroller_image", 11)]],
                        {},
                    ),
                    22: ("wagtail.blocks.ListBlock", (21,), {}),
                    23: ("blowcomotion.chooser_blocks.EventChooserBlock", (), {}),
                    24: (
                        "wagtail.blocks.ListBlock",
                        (23,),
                        {
                            "help_text": "Events that are not associated with Gig-o-Matic"
                        },
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [[("scroller_title", 19), ("gigo_gigs", 22), ("events", 24)]],
                        {},
                    ),
                    26: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    27: ("wagtail.blocks.StructBlock", [[("image", 26)]], {}),
                    28: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    29: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 26),
                                ("top_line", 28),
                                ("middle_line", 28),
                                ("bottom_line", 28),
                                ("youtube_url", 29),
                            ]
                        ],
                        {},
                    ),
                    31: (
                        "wagtail.blocks.ListBlock",
                        (26,),
                        {
                            "help_text": "Select images to display in the banner.",
                            "max_num": 7,
                            "min_num": 7,
                        },
                    ),
                    32: ("wagtail.blocks.StructBlock", [[("images", 31)]], {}),
                    33: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 26),
                                ("header", 28),
                                ("subheader", 33),
                                ("author", 28),
                            ]
                        ],
                        {},
                    ),
                    35: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the headline for the upcoming public gigs.",
                            "required": False,
                        },
                    ),
                    36: ("wagtail.blocks.StructBlock", [[("headline", 35)]], {}),
                },
                null=True,
            ),
        ),
    ]
