# Generated by Django 5.1.6 on 2025-04-19 20:27

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blowcomotion", "0001_squashed_0048_alter_blankcanvaspage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blankcanvaspage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("accordion_list", 4),
                    ("column_layout", 15),
                    ("countdown", 23),
                    ("events", 30),
                    ("full_width_image", 32),
                    ("hero", 34),
                    ("horizontal_rule", 9),
                    ("multi_image_banner", 36),
                    ("quoted_image", 38),
                    ("rich_text", 7),
                    ("spacer", 10),
                    ("upcoming_events", 40),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("content", 1)]],
                        {},
                    ),
                    3: ("wagtail.blocks.ListBlock", (2,), {}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("content", 3)]],
                        {},
                    ),
                    5: ("wagtail.blocks.RichTextBlock", (), {}),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                            ]
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("rich_text", 5), ("align", 6)]],
                        {},
                    ),
                    8: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"template": "blocks/image_block.html"},
                    ),
                    9: ("blowcomotion.blocks.HorizontalRuleBlock", (), {}),
                    10: ("blowcomotion.blocks.SpacerBlock", (), {}),
                    11: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("accordion_list", 4),
                                ("rich_text", 7),
                                ("image", 8),
                                ("horizontal_rule", 9),
                                ("spacer", 10),
                            ]
                        ],
                        {"required": False},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("left_column", 11), ("right_column", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("left_column", 11),
                                ("middle_column", 11),
                                ("right_column", 11),
                            ]
                        ],
                        {},
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("left_column", 11),
                                ("middle_column", 11),
                                ("right_column", 11),
                                ("middle_left_column", 11),
                                ("middle_right_column", 11),
                            ]
                        ],
                        {},
                    ),
                    15: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("two_column", 12),
                                ("three_column", 13),
                                ("four_column", 14),
                            ]
                        ],
                        {},
                    ),
                    16: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    17: (
                        "wagtail.blocks.DateBlock",
                        (),
                        {"help_text": "Enter the date for the countdown."},
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the top line text for the countdown.",
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the sub line text for the countdown.",
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the text for the button.",
                            "required": False,
                        },
                    ),
                    21: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Enter the URL for the button.",
                            "required": False,
                        },
                    ),
                    22: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("_self", "Same Tab"), ("_blank", "New Tab")],
                            "help_text": "Select the target for the button.",
                        },
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_image", 16),
                                ("countdown_date", 17),
                                ("head_line", 18),
                                ("sub_line", 19),
                                ("button_text", 20),
                                ("button_url", 21),
                                ("button_target", 22),
                            ]
                        ],
                        {},
                    ),
                    24: ("wagtail.blocks.CharBlock", (), {}),
                    25: ("blowcomotion.chooser_blocks.GigoGigChooserBlock", (), {}),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("details", 25), ("event_scroller_image", 16)]],
                        {},
                    ),
                    27: ("wagtail.blocks.ListBlock", (26,), {}),
                    28: ("blowcomotion.chooser_blocks.EventChooserBlock", (), {}),
                    29: (
                        "wagtail.blocks.ListBlock",
                        (28,),
                        {
                            "help_text": "Events that are not associated with Gig-o-Matic"
                        },
                    ),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [[("scroller_title", 24), ("gigo_gigs", 27), ("events", 29)]],
                        {},
                    ),
                    31: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    32: ("wagtail.blocks.StructBlock", [[("image", 31)]], {}),
                    33: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 31),
                                ("top_line", 0),
                                ("middle_line", 0),
                                ("bottom_line", 0),
                                ("youtube_url", 33),
                            ]
                        ],
                        {},
                    ),
                    35: (
                        "wagtail.blocks.ListBlock",
                        (31,),
                        {
                            "help_text": "Select images to display in the banner.",
                            "max_num": 7,
                            "min_num": 7,
                        },
                    ),
                    36: ("wagtail.blocks.StructBlock", [[("images", 35)]], {}),
                    37: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 31),
                                ("header", 0),
                                ("subheader", 37),
                                ("author", 0),
                            ]
                        ],
                        {},
                    ),
                    39: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the headline for the upcoming public gigs.",
                            "required": False,
                        },
                    ),
                    40: ("wagtail.blocks.StructBlock", [[("headline", 39)]], {}),
                },
                null=True,
            ),
        ),
    ]
