# Generated by Django 5.1.6 on 2025-04-21 02:23

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blowcomotion", "0049_alter_blankcanvaspage_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactFormSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("date_submitted", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="contact_form_email_recipients",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated list of email addresses to receive contact form submissions",
                max_length=1024,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="blankcanvaspage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("accordion_list", 4),
                    ("column_layout", 19),
                    ("contact_form", 8),
                    ("countdown", 26),
                    ("events", 33),
                    ("full_width_image", 35),
                    ("hero", 37),
                    ("horizontal_rule", 13),
                    ("multi_image_banner", 39),
                    ("quoted_image", 41),
                    ("rich_text", 11),
                    ("spacer", 14),
                    ("upcoming_events", 43),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("content", 1)]],
                        {},
                    ),
                    3: ("wagtail.blocks.ListBlock", (2,), {}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("content", 3)]],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the title for the contact form.",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Enter the description for the contact form.",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the text for the button.",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 5), ("description", 6), ("button_text", 7)]],
                        {},
                    ),
                    9: ("wagtail.blocks.RichTextBlock", (), {}),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                            ]
                        },
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("rich_text", 9), ("align", 10)]],
                        {},
                    ),
                    12: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"template": "blocks/image_block.html"},
                    ),
                    13: ("blowcomotion.blocks.HorizontalRuleBlock", (), {}),
                    14: ("blowcomotion.blocks.SpacerBlock", (), {}),
                    15: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("accordion_list", 4),
                                ("contact_form", 8),
                                ("rich_text", 11),
                                ("image", 12),
                                ("horizontal_rule", 13),
                                ("spacer", 14),
                            ]
                        ],
                        {"required": False},
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("left_column", 15), ("right_column", 15)]],
                        {},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("left_column", 15),
                                ("middle_column", 15),
                                ("right_column", 15),
                            ]
                        ],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("left_column", 15),
                                ("middle_column", 15),
                                ("right_column", 15),
                                ("middle_left_column", 15),
                                ("middle_right_column", 15),
                            ]
                        ],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("two_column", 16),
                                ("three_column", 17),
                                ("four_column", 18),
                            ]
                        ],
                        {},
                    ),
                    20: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    21: (
                        "wagtail.blocks.DateBlock",
                        (),
                        {"help_text": "Enter the date for the countdown."},
                    ),
                    22: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the top line text for the countdown.",
                            "required": False,
                        },
                    ),
                    23: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the sub line text for the countdown.",
                            "required": False,
                        },
                    ),
                    24: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Enter the URL for the button.",
                            "required": False,
                        },
                    ),
                    25: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("_self", "Same Tab"), ("_blank", "New Tab")],
                            "help_text": "Select the target for the button.",
                        },
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_image", 20),
                                ("countdown_date", 21),
                                ("head_line", 22),
                                ("sub_line", 23),
                                ("button_text", 7),
                                ("button_url", 24),
                                ("button_target", 25),
                            ]
                        ],
                        {},
                    ),
                    27: ("wagtail.blocks.CharBlock", (), {}),
                    28: ("blowcomotion.chooser_blocks.GigoGigChooserBlock", (), {}),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [[("details", 28), ("event_scroller_image", 20)]],
                        {},
                    ),
                    30: ("wagtail.blocks.ListBlock", (29,), {}),
                    31: ("blowcomotion.chooser_blocks.EventChooserBlock", (), {}),
                    32: (
                        "wagtail.blocks.ListBlock",
                        (31,),
                        {
                            "help_text": "Events that are not associated with Gig-o-Matic"
                        },
                    ),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [[("scroller_title", 27), ("gigo_gigs", 30), ("events", 32)]],
                        {},
                    ),
                    34: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    35: ("wagtail.blocks.StructBlock", [[("image", 34)]], {}),
                    36: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    37: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 34),
                                ("top_line", 0),
                                ("middle_line", 0),
                                ("bottom_line", 0),
                                ("youtube_url", 36),
                            ]
                        ],
                        {},
                    ),
                    38: (
                        "wagtail.blocks.ListBlock",
                        (34,),
                        {
                            "help_text": "Select images to display in the banner.",
                            "max_num": 7,
                            "min_num": 7,
                        },
                    ),
                    39: ("wagtail.blocks.StructBlock", [[("images", 38)]], {}),
                    40: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 34),
                                ("header", 0),
                                ("subheader", 40),
                                ("author", 0),
                            ]
                        ],
                        {},
                    ),
                    42: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the headline for the upcoming public gigs.",
                            "required": False,
                        },
                    ),
                    43: ("wagtail.blocks.StructBlock", [[("headline", 42)]], {}),
                },
                null=True,
            ),
        ),
    ]
