# Generated by Django 5.1.6 on 2025-04-22 02:58

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blowcomotion", "0050_contactformsubmission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="venmo_donate_url",
            field=models.URLField(
                blank=True, help_text="URL to Venmo donation page", null=True
            ),
        ),
        migrations.AlterField(
            model_name="blankcanvaspage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("accordion_list", 4),
                    ("column_layout", 22),
                    ("contact_form", 8),
                    ("countdown", 29),
                    ("events", 36),
                    ("full_width_image", 38),
                    ("hero", 40),
                    ("horizontal_rule", 9),
                    ("multi_image_banner", 42),
                    ("paypal_donate_button", 12),
                    ("quoted_image", 44),
                    ("rich_text", 15),
                    ("spacer", 16),
                    ("upcoming_events", 46),
                    ("venmo_donate_button", 17),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("content", 1)]],
                        {},
                    ),
                    3: ("wagtail.blocks.ListBlock", (2,), {}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("content", 3)]],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the title for the contact form.",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Enter the description for the contact form.",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the text for the button.",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 5), ("description", 6), ("button_text", 7)]],
                        {},
                    ),
                    9: ("blowcomotion.blocks.HorizontalRuleBlock", (), {}),
                    10: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"template": "blocks/image_block.html"},
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                            ],
                            "help_text": "Select the alignment for the button.",
                        },
                    ),
                    12: ("wagtail.blocks.StructBlock", [[("alignment", 11)]], {}),
                    13: ("wagtail.blocks.RichTextBlock", (), {}),
                    14: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                            ]
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("rich_text", 13), ("align", 14)]],
                        {},
                    ),
                    16: ("blowcomotion.blocks.SpacerBlock", (), {}),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [[("button_text", 7), ("alignment", 11)]],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("accordion_list", 4),
                                ("contact_form", 8),
                                ("horizontal_rule", 9),
                                ("image", 10),
                                ("paypal_donate_button", 12),
                                ("rich_text", 15),
                                ("spacer", 16),
                                ("venmo_donate_button", 17),
                            ]
                        ],
                        {"required": False},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("left_column", 18), ("right_column", 18)]],
                        {},
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("left_column", 18),
                                ("middle_column", 18),
                                ("right_column", 18),
                            ]
                        ],
                        {},
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("left_column", 18),
                                ("middle_column", 18),
                                ("right_column", 18),
                                ("middle_left_column", 18),
                                ("middle_right_column", 18),
                            ]
                        ],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("two_column", 19),
                                ("three_column", 20),
                                ("four_column", 21),
                            ]
                        ],
                        {},
                    ),
                    23: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    24: (
                        "wagtail.blocks.DateBlock",
                        (),
                        {"help_text": "Enter the date for the countdown."},
                    ),
                    25: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the top line text for the countdown.",
                            "required": False,
                        },
                    ),
                    26: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the sub line text for the countdown.",
                            "required": False,
                        },
                    ),
                    27: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Enter the URL for the button.",
                            "required": False,
                        },
                    ),
                    28: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("_self", "Same Tab"), ("_blank", "New Tab")],
                            "help_text": "Select the target for the button.",
                        },
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_image", 23),
                                ("countdown_date", 24),
                                ("head_line", 25),
                                ("sub_line", 26),
                                ("button_text", 7),
                                ("button_url", 27),
                                ("button_target", 28),
                            ]
                        ],
                        {},
                    ),
                    30: ("wagtail.blocks.CharBlock", (), {}),
                    31: ("blowcomotion.chooser_blocks.GigoGigChooserBlock", (), {}),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [[("details", 31), ("event_scroller_image", 23)]],
                        {},
                    ),
                    33: ("wagtail.blocks.ListBlock", (32,), {}),
                    34: ("blowcomotion.chooser_blocks.EventChooserBlock", (), {}),
                    35: (
                        "wagtail.blocks.ListBlock",
                        (34,),
                        {
                            "help_text": "Events that are not associated with Gig-o-Matic"
                        },
                    ),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [[("scroller_title", 30), ("gigo_gigs", 33), ("events", 35)]],
                        {},
                    ),
                    37: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    38: ("wagtail.blocks.StructBlock", [[("image", 37)]], {}),
                    39: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    40: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 37),
                                ("top_line", 0),
                                ("middle_line", 0),
                                ("bottom_line", 0),
                                ("youtube_url", 39),
                            ]
                        ],
                        {},
                    ),
                    41: (
                        "wagtail.blocks.ListBlock",
                        (37,),
                        {
                            "help_text": "Select images to display in the banner.",
                            "max_num": 7,
                            "min_num": 7,
                        },
                    ),
                    42: ("wagtail.blocks.StructBlock", [[("images", 41)]], {}),
                    43: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    44: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 37),
                                ("header", 0),
                                ("subheader", 43),
                                ("author", 0),
                            ]
                        ],
                        {},
                    ),
                    45: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the headline for the upcoming public gigs.",
                            "required": False,
                        },
                    ),
                    46: ("wagtail.blocks.StructBlock", [[("headline", 45)]], {}),
                },
                null=True,
            ),
        ),
    ]
