# Generated by Django 5.1.6 on 2025-04-22 20:03

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blowcomotion", "0051_sitesettings_venmo_donate_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blankcanvaspage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("accordion_list", 4),
                    ("button", 10),
                    ("column_layout", 26),
                    ("contact_form", 13),
                    ("countdown", 31),
                    ("events", 38),
                    ("full_width_image", 40),
                    ("hero", 42),
                    ("horizontal_rule", 14),
                    ("multi_image_banner", 44),
                    ("paypal_donate_button", 16),
                    ("quoted_image", 46),
                    ("rich_text", 19),
                    ("spacer", 20),
                    ("upcoming_events", 48),
                    ("venmo_donate_button", 21),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("content", 1)]],
                        {},
                    ),
                    3: ("wagtail.blocks.ListBlock", (2,), {}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("content", 3)]],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the text for the button.",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Enter the URL for the button.",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("_self", "Same Tab"), ("_blank", "New Tab")],
                            "help_text": "Select the target for the button.",
                        },
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                            ],
                            "help_text": "Select the alignment for the button.",
                        },
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("half", "Half"), ("full", "Full")],
                            "help_text": "Select the width for the button.",
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("button_text", 5),
                                ("button_url", 6),
                                ("button_target", 7),
                                ("button_alignment", 8),
                                ("button_width", 9),
                            ]
                        ],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the title for the contact form.",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Enter the description for the contact form.",
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 11), ("description", 12), ("button_text", 5)]],
                        {},
                    ),
                    14: ("blowcomotion.blocks.HorizontalRuleBlock", (), {}),
                    15: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"template": "blocks/image_block.html"},
                    ),
                    16: ("wagtail.blocks.StructBlock", [[("alignment", 8)]], {}),
                    17: ("wagtail.blocks.RichTextBlock", (), {}),
                    18: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                            ]
                        },
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("rich_text", 17), ("align", 18)]],
                        {},
                    ),
                    20: ("blowcomotion.blocks.SpacerBlock", (), {}),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [[("button_text", 5), ("alignment", 8)]],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("accordion_list", 4),
                                ("button", 10),
                                ("contact_form", 13),
                                ("horizontal_rule", 14),
                                ("image", 15),
                                ("paypal_donate_button", 16),
                                ("rich_text", 19),
                                ("spacer", 20),
                                ("venmo_donate_button", 21),
                            ]
                        ],
                        {"required": False},
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("left_column", 22), ("right_column", 22)]],
                        {},
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("left_column", 22),
                                ("middle_column", 22),
                                ("right_column", 22),
                            ]
                        ],
                        {},
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("left_column", 22),
                                ("middle_column", 22),
                                ("right_column", 22),
                                ("middle_left_column", 22),
                                ("middle_right_column", 22),
                            ]
                        ],
                        {},
                    ),
                    26: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("two_column", 23),
                                ("three_column", 24),
                                ("four_column", 25),
                            ]
                        ],
                        {},
                    ),
                    27: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    28: (
                        "wagtail.blocks.DateBlock",
                        (),
                        {"help_text": "Enter the date for the countdown."},
                    ),
                    29: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the top line text for the countdown.",
                            "required": False,
                        },
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the sub line text for the countdown.",
                            "required": False,
                        },
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_image", 27),
                                ("countdown_date", 28),
                                ("head_line", 29),
                                ("sub_line", 30),
                                ("button_text", 5),
                                ("button_url", 6),
                                ("button_target", 7),
                            ]
                        ],
                        {},
                    ),
                    32: ("wagtail.blocks.CharBlock", (), {}),
                    33: ("blowcomotion.chooser_blocks.GigoGigChooserBlock", (), {}),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [[("details", 33), ("event_scroller_image", 27)]],
                        {},
                    ),
                    35: ("wagtail.blocks.ListBlock", (34,), {}),
                    36: ("blowcomotion.chooser_blocks.EventChooserBlock", (), {}),
                    37: (
                        "wagtail.blocks.ListBlock",
                        (36,),
                        {
                            "help_text": "Events that are not associated with Gig-o-Matic"
                        },
                    ),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [[("scroller_title", 32), ("gigo_gigs", 35), ("events", 37)]],
                        {},
                    ),
                    39: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    40: ("wagtail.blocks.StructBlock", [[("image", 39)]], {}),
                    41: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 39),
                                ("top_line", 0),
                                ("middle_line", 0),
                                ("bottom_line", 0),
                                ("youtube_url", 41),
                            ]
                        ],
                        {},
                    ),
                    43: (
                        "wagtail.blocks.ListBlock",
                        (39,),
                        {
                            "help_text": "Select images to display in the banner.",
                            "max_num": 7,
                            "min_num": 7,
                        },
                    ),
                    44: ("wagtail.blocks.StructBlock", [[("images", 43)]], {}),
                    45: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    46: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 39),
                                ("header", 0),
                                ("subheader", 45),
                                ("author", 0),
                            ]
                        ],
                        {},
                    ),
                    47: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the headline for the upcoming public gigs.",
                            "required": False,
                        },
                    ),
                    48: ("wagtail.blocks.StructBlock", [[("headline", 47)]], {}),
                },
                null=True,
            ),
        ),
    ]
