# Generated by Django 5.1.6 on 2025-04-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blowcomotion", "0053_feedbackformsubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbackformsubmission",
            name="submitted_from_page",
            field=models.CharField(
                blank=True,
                help_text="The URL of the page from which the feedback was submitted",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contactformsubmission",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="contactformsubmission",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contactformsubmission",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="feedbackformsubmission",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="feedbackformsubmission",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="feedbackformsubmission",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
