# Generated by Django 5.1.6 on 2025-05-06 17:28

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blowcomotion", "0054_feedbackformsubmission_submitted_from_page_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="song",
            name="form",
            field=models.TextField(
                blank=True,
                help_text="e.g. 'Intro, Verse, Chorus, Bridge, Outro or AABA'",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="source_band",
            field=models.CharField(
                blank=True,
                help_text="e.g. 'Rebirth Brass Band', 'The Beatles', 'The Rolling Stones', etc.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="tempo",
            field=models.IntegerField(
                blank=True, help_text="Tempo in BPM (Beats Per Minute)", null=True
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="tonality",
            field=models.CharField(
                blank=True,
                choices=[("major", "Major"), ("minor", "Minor"), ("blues", "Blues")],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="key_signature",
            field=models.CharField(
                blank=True,
                choices=[
                    ("C", "C"),
                    ("F", "F"),
                    ("Bb", "Bb"),
                    ("Eb", "Eb"),
                    ("Ab", "Ab"),
                    ("Db", "Db"),
                    ("Gb", "Gb"),
                    ("G", "G"),
                    ("D", "D"),
                    ("A", "A"),
                    ("E", "E"),
                    ("B", "B"),
                    ("F#", "F#"),
                    ("C#", "C#"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="time_signature",
            field=models.CharField(
                blank=True,
                choices=[
                    ("4/4", "4/4"),
                    ("3/4", "3/4"),
                    ("2/4", "2/4"),
                    ("2/2", "2/2"),
                    ("6/8", "6/8"),
                    ("12/8", "12/8"),
                    ("5/4", "5/4"),
                    ("7/8", "7/8"),
                    ("9/8", "9/8"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="SongSoloist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blowcomotion.member",
                    ),
                ),
                (
                    "song",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soloists",
                        to="blowcomotion.song",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
