# Generated by Django 5.1.6 on 2025-05-06 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "blowcomotion",
            "0055_song_active_song_form_song_source_band_song_tempo_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="emergency_contact",
            field=models.TextField(
                blank=True,
                help_text="Name and phone number of emergency contact",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="last_seen",
            field=models.DateField(
                blank=True,
                help_text="This field auto-populates whenever attendance is taken.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="phone",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="renting",
            field=models.BooleanField(
                default=False, help_text="Is the member renting an instrument?"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="separation_date",
            field=models.DateField(
                blank=True,
                help_text="Date of separation from the organization.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="state",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="zip_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
