# Generated by Django 5.1.6 on 2025-06-03 21:57

import blowcomotion.models
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blowcomotion", "0064_sitesettings_patreon_url_and_more"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", wagtail.fields.RichTextField(blank=True, null=True)),
                (
                    "expiration_date",
                    models.DateField(
                        blank=True,
                        default=blowcomotion.models.get_default_expiration_date,
                        help_text="Date when the banner will no longer be displayed. Leave blank for no expiration.",
                        null=True,
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
