# Generated by Django 5.1.6 on 2025-06-18 04:21

# In your migration file:
from django.db import migrations

from wagtail.blocks.migrations.migrate_operation import MigrateStreamData
from wagtail.blocks.migrations.operations import RenameStreamChildrenOperation
from datetime import datetime

class Migration(migrations.Migration):
    dependencies = [
        ("blowcomotion", "0065_notificationbanner"),
    ]

    operations = [
        MigrateStreamData(
            app_name="blowcomotion",
            model_name="BlankCanvasPage",
            field_name="body",
            operations_and_block_paths=[
                (RenameStreamChildrenOperation(old_name="image", new_name="image_deprecated"), "column_layout.three_column.left_column"),
            ]
        ),
        MigrateStreamData(
            app_name="blowcomotion",
            model_name="BlankCanvasPage",
            field_name="body",
            operations_and_block_paths=[
                (RenameStreamChildrenOperation(old_name="image", new_name="image_deprecated"), "column_layout.three_column.middle_column"),
            ]
        ),
        MigrateStreamData(
            app_name="blowcomotion",
            model_name="BlankCanvasPage",
            field_name="body",
            operations_and_block_paths=[
                (RenameStreamChildrenOperation(old_name="image", new_name="image_deprecated"), "column_layout.three_column.right_column"),
            ]
        ),
        MigrateStreamData(
            app_name="blowcomotion",
            model_name="BlankCanvasPage",
            field_name="body",
            operations_and_block_paths=[
                (RenameStreamChildrenOperation(old_name="image", new_name="image_deprecated"), "column_layout.two_column.left_column"),
            ]
        ),
        MigrateStreamData(
            app_name="blowcomotion",
            model_name="BlankCanvasPage",
            field_name="body",
            operations_and_block_paths=[
                (RenameStreamChildrenOperation(old_name="image", new_name="image_deprecated"), "column_layout.two_column.right_column"),
            ]
        ),
    ]
