# Generated by Django 5.1.6 on 2025-06-18 05:16

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blowcomotion", "0066_alter_blankcanvaspage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blankcanvaspage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("accordion_list", 4),
                    ("button", 10),
                    ("column_layout", 33),
                    ("contact_form", 17),
                    ("countdown", 38),
                    ("events", 45),
                    ("full_width_image", 20),
                    ("hero", 47),
                    ("horizontal_rule", 13),
                    ("image", 20),
                    ("jukebox", 53),
                    ("multi_image_banner", 55),
                    ("patreon_button", 27),
                    ("paypal_donate_button", 26),
                    ("quoted_image", 56),
                    ("rich_text", 23),
                    ("adjustable_spacer", 12),
                    ("spacer", 24),
                    ("square_donate_button", 27),
                    ("upcoming_events", 58),
                    ("venmo_donate_button", 27),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("content", 1)]],
                        {},
                    ),
                    3: ("wagtail.blocks.ListBlock", (2,), {}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("content", 3)]],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the text for the button.",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Enter the URL for the button.",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("_self", "Same Tab"), ("_blank", "New Tab")],
                            "help_text": "Select the target for the button.",
                        },
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                            ],
                            "help_text": "Select the alignment for the button.",
                        },
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("half", "Half"), ("full", "Full")],
                            "help_text": "Select the width for the button.",
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("button_text", 5),
                                ("button_url", 6),
                                ("button_target", 7),
                                ("button_alignment", 8),
                                ("button_width", 9),
                            ]
                        ],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 20,
                            "help_text": "Enter the height of the spacer in pixels.",
                            "min_value": 1,
                        },
                    ),
                    12: ("wagtail.blocks.StructBlock", [[("height", 11)]], {}),
                    13: ("blowcomotion.blocks.HorizontalRuleBlock", (), {}),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the title for the contact form.",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Enter the description for the contact form.",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "Include an opt-in checkbox for the newsletter.",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 14),
                                ("description", 15),
                                ("button_text", 5),
                                ("newsletter_opt_in", 16),
                            ]
                        ],
                        {},
                    ),
                    18: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    19: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Optional: Link the image to a URL (e.g. merch page)",
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 18), ("url", 19)]],
                        {},
                    ),
                    21: ("wagtail.blocks.RichTextBlock", (), {}),
                    22: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                            ]
                        },
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [[("rich_text", 21), ("align", 22)]],
                        {},
                    ),
                    24: ("blowcomotion.blocks.SpacerBlock", (), {}),
                    25: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Donate with PayPal",
                            "help_text": "Enter the text for the button.",
                            "required": False,
                        },
                    ),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("button_alignment", 8),
                                ("button_width", 9),
                                ("button_text", 25),
                            ]
                        ],
                        {},
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("button_text", 5),
                                ("button_alignment", 8),
                                ("button_width", 9),
                            ]
                        ],
                        {},
                    ),
                    28: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("accordion_list", 4),
                                ("button", 10),
                                ("contact_form", 17),
                                ("horizontal_rule", 13),
                                ("image", 20),
                                ("rich_text", 23),
                                ("adjustable_spacer", 12),
                                ("spacer", 24),
                                ("paypal_donate_button", 26),
                                ("venmo_donate_button", 27),
                                ("square_donate_button", 27),
                                ("patreon_button", 27),
                            ]
                        ],
                        {"required": False},
                    ),
                    29: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("one-half", "One Half"),
                                ("one-third", "One Third"),
                                ("two-thirds", "Two Thirds"),
                            ]
                        },
                    ),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("left_column", 28),
                                ("right_column", 28),
                                ("left_column_width", 29),
                            ]
                        ],
                        {},
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("left_column", 28),
                                ("middle_column", 28),
                                ("right_column", 28),
                            ]
                        ],
                        {},
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("left_column", 28),
                                ("middle_left_column", 28),
                                ("middle_right_column", 28),
                                ("right_column", 28),
                            ]
                        ],
                        {},
                    ),
                    33: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("spacer", 12),
                                ("horizontal_rule", 13),
                                ("two_column", 30),
                                ("three_column", 31),
                                ("four_column", 32),
                            ]
                        ],
                        {},
                    ),
                    34: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    35: (
                        "wagtail.blocks.DateBlock",
                        (),
                        {"help_text": "Enter the date for the countdown."},
                    ),
                    36: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the top line text for the countdown.",
                            "required": False,
                        },
                    ),
                    37: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the sub line text for the countdown.",
                            "required": False,
                        },
                    ),
                    38: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_image", 34),
                                ("countdown_date", 35),
                                ("head_line", 36),
                                ("sub_line", 37),
                                ("button_text", 5),
                                ("button_url", 6),
                                ("button_target", 7),
                            ]
                        ],
                        {},
                    ),
                    39: ("wagtail.blocks.CharBlock", (), {}),
                    40: ("blowcomotion.chooser_blocks.GigoGigChooserBlock", (), {}),
                    41: (
                        "wagtail.blocks.StructBlock",
                        [[("details", 40), ("event_scroller_image", 34)]],
                        {},
                    ),
                    42: ("wagtail.blocks.ListBlock", (41,), {}),
                    43: ("blowcomotion.chooser_blocks.EventChooserBlock", (), {}),
                    44: (
                        "wagtail.blocks.ListBlock",
                        (43,),
                        {
                            "help_text": "Events that are not associated with Gig-o-Matic"
                        },
                    ),
                    45: (
                        "wagtail.blocks.StructBlock",
                        [[("scroller_title", 39), ("gigo_gigs", 42), ("events", 44)]],
                        {},
                    ),
                    46: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    47: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 18),
                                ("top_line", 0),
                                ("middle_line", 0),
                                ("bottom_line", 0),
                                ("youtube_url", 46),
                            ]
                        ],
                        {},
                    ),
                    48: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the foreground title text for the jukebox.",
                            "required": False,
                        },
                    ),
                    49: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the background title text for the jukebox.",
                            "required": False,
                        },
                    ),
                    50: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Select the image for the jukebox.",
                            "required": False,
                        },
                    ),
                    51: ("blowcomotion.chooser_blocks.SongChooserBlock", (), {}),
                    52: (
                        "wagtail.blocks.ListBlock",
                        (51,),
                        {
                            "help_text": "Select the songs for the jukebox. A song must have a recording for it to show up in the jukebox.",
                            "min_num": 1,
                        },
                    ),
                    53: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("foreground_text", 48),
                                ("background_text", 49),
                                ("jukebox_image", 50),
                                ("tracks", 52),
                            ]
                        ],
                        {},
                    ),
                    54: (
                        "wagtail.blocks.ListBlock",
                        (18,),
                        {
                            "help_text": "Select images to display in the banner.",
                            "max_num": 7,
                            "min_num": 7,
                        },
                    ),
                    55: ("wagtail.blocks.StructBlock", [[("images", 54)]], {}),
                    56: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 18),
                                ("header", 0),
                                ("subheader", 1),
                                ("author", 0),
                            ]
                        ],
                        {},
                    ),
                    57: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the headline for the upcoming public gigs.",
                            "required": False,
                        },
                    ),
                    58: ("wagtail.blocks.StructBlock", [[("headline", 57)]], {}),
                },
                null=True,
            ),
        ),
    ]
