# Generated by Django 5.1.6 on 2025-06-18 04:35

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blowcomotion", "0066_auto_20250617_2321"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blankcanvaspage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("accordion_list", 4),
                    ("button", 10),
                    ("column_layout", 34),
                    ("contact_form", 17),
                    ("countdown", 39),
                    ("events", 46),
                    ("full_width_image", 21),
                    ("hero", 48),
                    ("horizontal_rule", 13),
                    ("image", 21),
                    ("jukebox", 54),
                    ("multi_image_banner", 56),
                    ("patreon_button", 28),
                    ("paypal_donate_button", 27),
                    ("quoted_image", 57),
                    ("rich_text", 24),
                    ("adjustable_spacer", 12),
                    ("spacer", 25),
                    ("square_donate_button", 28),
                    ("upcoming_events", 59),
                    ("venmo_donate_button", 28),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("content", 1)]],
                        {},
                    ),
                    3: ("wagtail.blocks.ListBlock", (2,), {}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("content", 3)]],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the text for the button.",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Enter the URL for the button.",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("_self", "Same Tab"), ("_blank", "New Tab")],
                            "help_text": "Select the target for the button.",
                        },
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                            ],
                            "help_text": "Select the alignment for the button.",
                        },
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("half", "Half"), ("full", "Full")],
                            "help_text": "Select the width for the button.",
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("button_text", 5),
                                ("button_url", 6),
                                ("button_target", 7),
                                ("button_alignment", 8),
                                ("button_width", 9),
                            ]
                        ],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 20,
                            "help_text": "Enter the height of the spacer in pixels.",
                            "min_value": 1,
                        },
                    ),
                    12: ("wagtail.blocks.StructBlock", [[("height", 11)]], {}),
                    13: ("blowcomotion.blocks.HorizontalRuleBlock", (), {}),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the title for the contact form.",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Enter the description for the contact form.",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "Include an opt-in checkbox for the newsletter.",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 14),
                                ("description", 15),
                                ("button_text", 5),
                                ("newsletter_opt_in", 16),
                            ]
                        ],
                        {},
                    ),
                    18: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Deprecated: Use new Image block instead.",
                            "template": "blocks/image_block.html",
                        },
                    ),
                    19: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    20: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Optional: Link the image to a URL (e.g. merch page)",
                            "required": False,
                        },
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 19), ("url", 20)]],
                        {},
                    ),
                    22: ("wagtail.blocks.RichTextBlock", (), {}),
                    23: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                            ]
                        },
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("rich_text", 22), ("align", 23)]],
                        {},
                    ),
                    25: ("blowcomotion.blocks.SpacerBlock", (), {}),
                    26: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Donate with PayPal",
                            "help_text": "Enter the text for the button.",
                            "required": False,
                        },
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("button_alignment", 8),
                                ("button_width", 9),
                                ("button_text", 26),
                            ]
                        ],
                        {},
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("button_text", 5),
                                ("button_alignment", 8),
                                ("button_width", 9),
                            ]
                        ],
                        {},
                    ),
                    29: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("accordion_list", 4),
                                ("button", 10),
                                ("contact_form", 17),
                                ("horizontal_rule", 13),
                                ("image_deprecated", 18),
                                ("image", 21),
                                ("rich_text", 24),
                                ("adjustable_spacer", 12),
                                ("spacer", 25),
                                ("paypal_donate_button", 27),
                                ("venmo_donate_button", 28),
                                ("square_donate_button", 28),
                                ("patreon_button", 28),
                            ]
                        ],
                        {"required": False},
                    ),
                    30: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("one-half", "One Half"),
                                ("one-third", "One Third"),
                                ("two-thirds", "Two Thirds"),
                            ]
                        },
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("left_column", 29),
                                ("right_column", 29),
                                ("left_column_width", 30),
                            ]
                        ],
                        {},
                    ),
                    32: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("left_column", 29),
                                ("middle_column", 29),
                                ("right_column", 29),
                            ]
                        ],
                        {},
                    ),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("left_column", 29),
                                ("middle_left_column", 29),
                                ("middle_right_column", 29),
                                ("right_column", 29),
                            ]
                        ],
                        {},
                    ),
                    34: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("spacer", 12),
                                ("horizontal_rule", 13),
                                ("two_column", 31),
                                ("three_column", 32),
                                ("four_column", 33),
                            ]
                        ],
                        {},
                    ),
                    35: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    36: (
                        "wagtail.blocks.DateBlock",
                        (),
                        {"help_text": "Enter the date for the countdown."},
                    ),
                    37: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the top line text for the countdown.",
                            "required": False,
                        },
                    ),
                    38: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the sub line text for the countdown.",
                            "required": False,
                        },
                    ),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_image", 35),
                                ("countdown_date", 36),
                                ("head_line", 37),
                                ("sub_line", 38),
                                ("button_text", 5),
                                ("button_url", 6),
                                ("button_target", 7),
                            ]
                        ],
                        {},
                    ),
                    40: ("wagtail.blocks.CharBlock", (), {}),
                    41: ("blowcomotion.chooser_blocks.GigoGigChooserBlock", (), {}),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [[("details", 41), ("event_scroller_image", 35)]],
                        {},
                    ),
                    43: ("wagtail.blocks.ListBlock", (42,), {}),
                    44: ("blowcomotion.chooser_blocks.EventChooserBlock", (), {}),
                    45: (
                        "wagtail.blocks.ListBlock",
                        (44,),
                        {
                            "help_text": "Events that are not associated with Gig-o-Matic"
                        },
                    ),
                    46: (
                        "wagtail.blocks.StructBlock",
                        [[("scroller_title", 40), ("gigo_gigs", 43), ("events", 45)]],
                        {},
                    ),
                    47: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    48: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 19),
                                ("top_line", 0),
                                ("middle_line", 0),
                                ("bottom_line", 0),
                                ("youtube_url", 47),
                            ]
                        ],
                        {},
                    ),
                    49: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the foreground title text for the jukebox.",
                            "required": False,
                        },
                    ),
                    50: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the background title text for the jukebox.",
                            "required": False,
                        },
                    ),
                    51: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Select the image for the jukebox.",
                            "required": False,
                        },
                    ),
                    52: ("blowcomotion.chooser_blocks.SongChooserBlock", (), {}),
                    53: (
                        "wagtail.blocks.ListBlock",
                        (52,),
                        {
                            "help_text": "Select the songs for the jukebox. A song must have a recording for it to show up in the jukebox.",
                            "min_num": 1,
                        },
                    ),
                    54: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("foreground_text", 49),
                                ("background_text", 50),
                                ("jukebox_image", 51),
                                ("tracks", 53),
                            ]
                        ],
                        {},
                    ),
                    55: (
                        "wagtail.blocks.ListBlock",
                        (19,),
                        {
                            "help_text": "Select images to display in the banner.",
                            "max_num": 7,
                            "min_num": 7,
                        },
                    ),
                    56: ("wagtail.blocks.StructBlock", [[("images", 55)]], {}),
                    57: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 19),
                                ("header", 0),
                                ("subheader", 1),
                                ("author", 0),
                            ]
                        ],
                        {},
                    ),
                    58: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the headline for the upcoming public gigs.",
                            "required": False,
                        },
                    ),
                    59: ("wagtail.blocks.StructBlock", [[("headline", 58)]], {}),
                },
                null=True,
            ),
        ),
    ]
