# Generated by Django 5.1.6 on 2025-08-01 00:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blowcomotion", "0068_bookingformsubmission_donateformsubmission_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today)),
                (
                    "guest_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of guest/visitor (leave blank for members)",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="blowcomotion.member",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "member__last_name"],
                "unique_together": {("date", "member")},
            },
        ),
    ]
