# Generated by Django 5.1.6 on 2025-08-01 03:40

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blowcomotion", "0069_attendancerecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blankcanvaspage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("accordion_list", 4),
                    ("booking_form", 12),
                    ("button", 17),
                    ("column_layout", 49),
                    ("contact_form", 23),
                    ("countdown", 54),
                    ("donate_form", 27),
                    ("events", 61),
                    ("full_width_image", 36),
                    ("hero", 63),
                    ("horizontal_rule", 20),
                    ("image", 36),
                    ("join_band_form", 33),
                    ("jukebox", 71),
                    ("multi_image_banner", 73),
                    ("patreon_button", 43),
                    ("paypal_donate_button", 42),
                    ("quoted_image", 74),
                    ("rich_text", 39),
                    ("adjustable_spacer", 19),
                    ("spacer", 40),
                    ("square_donate_button", 43),
                    ("upcoming_events", 76),
                    ("venmo_donate_button", 43),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    1: ("wagtail.blocks.RichTextBlock", (), {"required": False}),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("content", 1)]],
                        {},
                    ),
                    3: ("wagtail.blocks.ListBlock", (2,), {}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("content", 3)]],
                        {},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the title for the booking form.",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Enter the description for the booking form.",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the text for the button.",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Your Name:",
                            "help_text": "Enter the label for the name field.",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Your Email:",
                            "help_text": "Enter the label for the email field.",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Tell us about your event:",
                            "help_text": "Enter the label for the message field.",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "Include an opt-in checkbox for the newsletter.",
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 5),
                                ("description", 6),
                                ("button_text", 7),
                                ("name_field_label", 8),
                                ("email_field_label", 9),
                                ("message_field_label", 10),
                                ("newsletter_opt_in", 11),
                            ]
                        ],
                        {"group": "Forms"},
                    ),
                    13: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Enter the URL for the button.",
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("_self", "Same Tab"), ("_blank", "New Tab")],
                            "help_text": "Select the target for the button.",
                        },
                    ),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                            ],
                            "help_text": "Select the alignment for the button.",
                        },
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("half", "Half"), ("full", "Full")],
                            "help_text": "Select the width for the button.",
                        },
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("button_text", 7),
                                ("button_url", 13),
                                ("button_target", 14),
                                ("button_alignment", 15),
                                ("button_width", 16),
                            ]
                        ],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 20,
                            "help_text": "Enter the height of the spacer in pixels.",
                            "min_value": 1,
                        },
                    ),
                    19: ("wagtail.blocks.StructBlock", [[("height", 18)]], {}),
                    20: ("blowcomotion.blocks.HorizontalRuleBlock", (), {}),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the title for the contact form.",
                            "required": False,
                        },
                    ),
                    22: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Enter the description for the contact form.",
                            "required": False,
                        },
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 21),
                                ("description", 22),
                                ("button_text", 7),
                                ("newsletter_opt_in", 11),
                            ]
                        ],
                        {"group": "Forms"},
                    ),
                    24: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the title for the donate form.",
                            "required": False,
                        },
                    ),
                    25: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Enter the description for the donate form.",
                            "required": False,
                        },
                    ),
                    26: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Message:",
                            "help_text": "Enter the label for the message field.",
                            "required": False,
                        },
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 24),
                                ("description", 25),
                                ("button_text", 7),
                                ("name_field_label", 8),
                                ("email_field_label", 9),
                                ("message_field_label", 26),
                                ("newsletter_opt_in", 11),
                            ]
                        ],
                        {"group": "Forms"},
                    ),
                    28: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the title for the join band form.",
                            "required": False,
                        },
                    ),
                    29: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "help_text": "Enter the description for the join band form.",
                            "required": False,
                        },
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "What instrument do you play?",
                            "help_text": "Enter the label for the instrument field.",
                            "required": False,
                        },
                    ),
                    31: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Would you like to rent an instrument?",
                            "help_text": "Enter the label for the instrument rental field.",
                            "required": False,
                        },
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Additional message/notes:",
                            "help_text": "Enter the label for the message field.",
                            "required": False,
                        },
                    ),
                    33: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 28),
                                ("description", 29),
                                ("button_text", 7),
                                ("instrument_field_label", 30),
                                ("instrument_rental_field_label", 31),
                                ("message_field_label", 32),
                                ("newsletter_opt_in", 11),
                            ]
                        ],
                        {"group": "Forms"},
                    ),
                    34: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    35: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Optional: Link the image to a URL (e.g. merch page)",
                            "required": False,
                        },
                    ),
                    36: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 34), ("url", 35)]],
                        {},
                    ),
                    37: ("wagtail.blocks.RichTextBlock", (), {}),
                    38: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                            ]
                        },
                    ),
                    39: (
                        "wagtail.blocks.StructBlock",
                        [[("rich_text", 37), ("align", 38)]],
                        {},
                    ),
                    40: ("blowcomotion.blocks.SpacerBlock", (), {}),
                    41: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Donate with PayPal",
                            "help_text": "Enter the text for the button.",
                            "required": False,
                        },
                    ),
                    42: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("button_alignment", 15),
                                ("button_width", 16),
                                ("button_text", 41),
                            ]
                        ],
                        {},
                    ),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("button_text", 7),
                                ("button_alignment", 15),
                                ("button_width", 16),
                            ]
                        ],
                        {},
                    ),
                    44: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("accordion_list", 4),
                                ("booking_form", 12),
                                ("button", 17),
                                ("contact_form", 23),
                                ("donate_form", 27),
                                ("join_band_form", 33),
                                ("horizontal_rule", 20),
                                ("image", 36),
                                ("rich_text", 39),
                                ("adjustable_spacer", 19),
                                ("spacer", 40),
                                ("paypal_donate_button", 42),
                                ("venmo_donate_button", 43),
                                ("square_donate_button", 43),
                                ("patreon_button", 43),
                            ]
                        ],
                        {"required": False},
                    ),
                    45: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("one-half", "One Half"),
                                ("one-third", "One Third"),
                                ("two-thirds", "Two Thirds"),
                            ]
                        },
                    ),
                    46: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("left_column", 44),
                                ("right_column", 44),
                                ("left_column_width", 45),
                            ]
                        ],
                        {},
                    ),
                    47: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("left_column", 44),
                                ("middle_column", 44),
                                ("right_column", 44),
                            ]
                        ],
                        {},
                    ),
                    48: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("left_column", 44),
                                ("middle_left_column", 44),
                                ("middle_right_column", 44),
                                ("right_column", 44),
                            ]
                        ],
                        {},
                    ),
                    49: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("spacer", 19),
                                ("horizontal_rule", 20),
                                ("two_column", 46),
                                ("three_column", 47),
                                ("four_column", 48),
                            ]
                        ],
                        {},
                    ),
                    50: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    51: (
                        "wagtail.blocks.DateBlock",
                        (),
                        {"help_text": "Enter the date for the countdown."},
                    ),
                    52: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the top line text for the countdown.",
                            "required": False,
                        },
                    ),
                    53: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the sub line text for the countdown.",
                            "required": False,
                        },
                    ),
                    54: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background_image", 50),
                                ("countdown_date", 51),
                                ("head_line", 52),
                                ("sub_line", 53),
                                ("button_text", 7),
                                ("button_url", 13),
                                ("button_target", 14),
                            ]
                        ],
                        {},
                    ),
                    55: ("wagtail.blocks.CharBlock", (), {}),
                    56: ("blowcomotion.chooser_blocks.GigoGigChooserBlock", (), {}),
                    57: (
                        "wagtail.blocks.StructBlock",
                        [[("details", 56), ("event_scroller_image", 50)]],
                        {},
                    ),
                    58: ("wagtail.blocks.ListBlock", (57,), {}),
                    59: ("blowcomotion.chooser_blocks.EventChooserBlock", (), {}),
                    60: (
                        "wagtail.blocks.ListBlock",
                        (59,),
                        {
                            "help_text": "Events that are not associated with Gig-o-Matic"
                        },
                    ),
                    61: (
                        "wagtail.blocks.StructBlock",
                        [[("scroller_title", 55), ("gigo_gigs", 58), ("events", 60)]],
                        {},
                    ),
                    62: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    63: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 34),
                                ("top_line", 0),
                                ("middle_line", 0),
                                ("bottom_line", 0),
                                ("youtube_url", 62),
                            ]
                        ],
                        {},
                    ),
                    64: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the foreground title text for the jukebox.",
                            "required": False,
                        },
                    ),
                    65: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the background title text for the jukebox.",
                            "required": False,
                        },
                    ),
                    66: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {
                            "help_text": "Select the image for the jukebox.",
                            "required": False,
                        },
                    ),
                    67: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Enable lazy loading for better performance. Audio files will only load when the user clicks play.",
                            "required": False,
                        },
                    ),
                    68: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Preload the first track's metadata for immediate playback. Only applies when lazy loading is enabled.",
                            "required": False,
                        },
                    ),
                    69: ("blowcomotion.chooser_blocks.SongChooserBlock", (), {}),
                    70: (
                        "wagtail.blocks.ListBlock",
                        (69,),
                        {
                            "help_text": "Select the songs for the jukebox. A song must have a recording for it to show up in the jukebox.",
                            "min_num": 1,
                        },
                    ),
                    71: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("foreground_text", 64),
                                ("background_text", 65),
                                ("jukebox_image", 66),
                                ("lazy_loading", 67),
                                ("preload_first_track", 68),
                                ("tracks", 70),
                            ]
                        ],
                        {},
                    ),
                    72: (
                        "wagtail.blocks.ListBlock",
                        (34,),
                        {
                            "help_text": "Select images to display in the banner.",
                            "max_num": 7,
                            "min_num": 7,
                        },
                    ),
                    73: ("wagtail.blocks.StructBlock", [[("images", 72)]], {}),
                    74: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 34),
                                ("header", 0),
                                ("subheader", 1),
                                ("author", 0),
                            ]
                        ],
                        {},
                    ),
                    75: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter the headline for the upcoming public gigs.",
                            "required": False,
                        },
                    ),
                    76: ("wagtail.blocks.StructBlock", [[("headline", 75)]], {}),
                },
                null=True,
            ),
        ),
    ]
