# Generated by Django 5.1.6 on 2025-08-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blowcomotion", "0070_alter_blankcanvaspage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="birthday",
        ),
        migrations.AddField(
            model_name="member",
            name="birth_day",
            field=models.IntegerField(
                blank=True, help_text="Birth day (1-31)", null=True
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="birth_month",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "January"),
                    (2, "February"),
                    (3, "March"),
                    (4, "April"),
                    (5, "May"),
                    (6, "June"),
                    (7, "July"),
                    (8, "August"),
                    (9, "September"),
                    (10, "October"),
                    (11, "November"),
                    (12, "December"),
                ],
                help_text="Birth month (1-12)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="birth_year",
            field=models.IntegerField(
                blank=True, help_text="Birth year (YYYY)", null=True
            ),
        ),
    ]
