# Generated by Django 5.1.6 on 2025-08-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blowcomotion", "0071_remove_member_birthday_member_birth_day_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="preferred_name",
            field=models.CharField(
                blank=True,
                help_text="Name the member prefers to be called (optional)",
                max_length=255,
                null=True,
            ),
        ),
    ]
