# Generated by Django 5.1.6 on 2025-08-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blowcomotion", "0072_member_preferred_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="attendance_password",
            field=models.CharField(
                blank=True,
                help_text="Password for accessing the attendance tracking system",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="birthdays_password",
            field=models.CharField(
                blank=True,
                help_text="Password for accessing the birthdays page",
                max_length=255,
                null=True,
            ),
        ),
    ]
