# Generated by Django 5.1.6 on 2025-10-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blowcomotion", "0073_sitesettings_attendance_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="inspired_by",
            field=models.TextField(
                blank=True,
                help_text="What event or person inspired this member to join the band",
                null=True,
            ),
        ),
    ]
