# Generated by Django 5.1.6 on 2025-08-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0073_sitesettings_attendance_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='birthday_summary_email_recipients',
            field=models.CharField(blank=True, help_text='Comma-separated list of email addresses to receive monthly birthday summary emails', max_length=1024, null=True),
        ),
    ]
