# Generated by Django 5.1.6 on 2025-10-08 00:55

import modelcluster.fields

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0074_member_inspired_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='primary_instrument',
            field=models.ForeignKey(blank=True, help_text='Primary instrument played by this member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_members', to='blowcomotion.instrument'),
        ),
        migrations.AlterField(
            model_name='memberinstrument',
            name='member',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_instruments', to='blowcomotion.member'),
        ),
    ]
