# Generated by Django 5.1.6 on 2025-10-08 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blowcomotion", "0076_migrate_instruments_to_primary_and_additional"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="favicon",
            field=models.ForeignKey(
                blank=True,
                help_text="Image used for the browser favicon. Upload a square image for best results.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="blowcomotion.customimage",
            ),
        ),
    ]
