# Generated by Django 5.1.6 on 2025-10-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0077_sitesettings_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='gigomatic_username',
            field=models.CharField(blank=True, help_text='Username used on Gig-O-Matic for this member', max_length=255, null=True),
        ),
    ]
