# Generated by Django 5.1.6 on 2025-11-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0079_alter_blankcanvaspage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='played_instrument',
            field=models.ForeignKey(
                blank=True,
                help_text='Instrument the member played for this attendance entry',
                null=True,
                on_delete=models.SET_NULL,
                related_name='attendance_records_as_played',
                to='blowcomotion.instrument',
            ),
        ),
    ]
