# Generated by Django 5.2.8 on 2025-11-28 07:05

import datetime

import modelcluster.fields
import modelsearch.index

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0080_attendancerecord_played_instrument'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='instrument_rental_notification_recipients',
            field=models.CharField(blank=True, help_text='Comma-separated list of email addresses to receive instrument rental notifications', max_length=1024, null=True),
        ),
        migrations.CreateModel(
            name='LibraryInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live', models.BooleanField(default=True, editable=False, verbose_name='live')),
                ('has_unpublished_changes', models.BooleanField(default=False, editable=False, verbose_name='has unpublished changes')),
                ('first_published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='first published at')),
                ('last_published_at', models.DateTimeField(editable=False, null=True, verbose_name='last published at')),
                ('go_live_at', models.DateTimeField(blank=True, null=True, verbose_name='go live date/time')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='expiry date/time')),
                ('expired', models.BooleanField(default=False, editable=False, verbose_name='expired')),
                ('locked', models.BooleanField(default=False, editable=False, verbose_name='locked')),
                ('locked_at', models.DateTimeField(editable=False, null=True, verbose_name='locked at')),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('needs_repair', 'Needs Repair/Unplayable'), ('out_for_repair', 'Out for Repair'), ('disposed', 'Disposed')], default='available', help_text='Current availability of this instrument', max_length=50)),
                ('serial_number', models.TextField(help_text='Serial number or other identifying marks')),
                ('rental_date', models.DateField(blank=True, help_text='Date the instrument was lent to the current member', null=True)),
                ('agreement_signed_date', models.DateField(blank=True, help_text='Date the rental agreement was signed', null=True)),
                ('review_date_6_month', models.DateField(blank=True, help_text='Six-month rental review date (auto-calculated)', null=True)),
                ('review_date_12_month', models.DateField(blank=True, help_text='Twelve-month rental review date (auto-calculated)', null=True)),
                ('patreon_active', models.BooleanField(default=False, help_text='Is the renter currently an active Patreon supporter?')),
                ('patreon_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly Patreon support amount', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('comments', models.TextField(blank=True, help_text='Additional context or maintenance notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.ForeignKey(help_text='Instrument type (e.g. Trombone, Trumpet)', on_delete=django.db.models.deletion.PROTECT, related_name='library_inventory', to='blowcomotion.instrument')),
                ('latest_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision')),
                ('live_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='live revision')),
                ('locked_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='locked by')),
                ('member', models.ForeignKey(blank=True, help_text='Person currently storing or borrowing this instrument', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rented_instruments', to='blowcomotion.member')),
            ],
            options={
                'verbose_name': 'Library Instrument',
                'verbose_name_plural': 'Library Instruments',
                'ordering': ['instrument__name', 'serial_number'],
            },
            bases=(models.Model, modelsearch.index.Indexed),
        ),
        migrations.CreateModel(
            name='InstrumentHistoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(default=datetime.date.today, help_text='Date of this event')),
                ('event_category', models.CharField(choices=[('acquisition', 'Acquisition'), ('out_for_repair', 'Out for Repair'), ('returned_from_repair', 'Returned from Repair'), ('out_for_loan', 'Out for Loan'), ('returned_from_loan', 'Returned from Loan'), ('location_check', 'Location Check'), ('rental_note', 'Rental Note'), ('return_note', 'Return Note'), ('disposal', 'Disposal')], help_text='Type of event', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Details about this event')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who created this log entry', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('library_instrument', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_logs', to='blowcomotion.libraryinstrument')),
            ],
            options={
                'verbose_name': 'Instrument History Log',
                'verbose_name_plural': 'Instrument History Logs',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LibraryInstrumentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='blowcomotion.customimage')),
                ('library_instrument', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='blowcomotion.libraryinstrument')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
