# Generated by Django 5.2.8 on 2025-11-29 03:18

import modelcluster.fields

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0081_sitesettings_instrument_rental_notification_recipients_and_more'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryInstrumentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('description', models.CharField(blank=True, help_text="e.g. 'Rental Agreement', 'Receipt', 'Return Inspection Form'", max_length=255)),
                ('uploaded_date', models.DateField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.document')),
                ('library_instrument', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_documents', to='blowcomotion.libraryinstrument')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
