# Generated by Django 5.2.8 on 2025-11-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0082_libraryinstrumentdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='renting',
            field=models.BooleanField(default=False, help_text='Is the member renting an instrument? (Auto-updated when instruments are rented/returned)'),
        ),
    ]
