# Generated by Django 5.2.8 on 2026-01-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0084_alter_blankcanvaspage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='attendance_cleanup_days',
            field=models.IntegerField(default=90, help_text='Number of days since last seeing a member to automatically mark them inactive when cleaning attendance records for the attendance system.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='attendance_cleanup_notification_recipients',
            field=models.CharField(blank=True, help_text='Comma-separated list of email addresses to receive attendance cleanup notifications', max_length=1024, null=True),
        ),
    ]
