# Generated by Django 5.2.8 on 2026-01-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0085_sitesettings_attendance_cleanup_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='birthday_summary_email_recipients',
            field=models.CharField(blank=True, help_text='Comma-separated list of email addresses to receive monthly birthday summary emails', max_length=1024, null=True),
        ),
    ]
