# Generated by Django 5.2.8 on 2026-01-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0086_sitesettings_birthday_summary_email_recipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='member_signup_notification_recipients',
            field=models.CharField(blank=True, help_text='Comma-separated list of email addresses to receive member signup notifications', max_length=1024, null=True),
        ),
    ]
