# Generated by Django 5.2.8 on 2026-02-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0087_sitesettings_member_signup_notification_recipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='gigomatic_id',
            field=models.IntegerField(blank=True, help_text='ID used on Gig-O-Matic for this member', null=True),
        ),
    ]
