# Generated by Django 5.2.8 on 2026-03-07 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0091_migrate_music_video_url_to_songvideo'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='is_part_uploaded',
        ),
        migrations.AlterField(
            model_name='chart',
            name='pdf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
    ]
