# Generated by Django 5.2.8 on 2026-03-27 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0096_alter_blankcanvaspage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentStorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='libraryinstrument',
            name='storage_location',
            field=models.ForeignKey(blank=True, help_text='Physical storage location for this instrument (e.g. organization locker). Leave blank if stored with member.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stored_instruments', to='blowcomotion.instrumentstoragelocation'),
        ),
    ]
