# Generated by Django 5.2.8 on 2026-06-05 05:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0099_alter_blankcanvaspage_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libraryinstrument',
            name='review_date_12_month',
        ),
        migrations.RemoveField(
            model_name='libraryinstrument',
            name='review_date_6_month',
        ),
        migrations.AddField(
            model_name='libraryinstrument',
            name='acquisition_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original cost of acquiring this instrument', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='libraryinstrument',
            name='current_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current estimated value of this instrument', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='libraryinstrument',
            name='replacement_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated cost to replace this instrument', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
