# Generated by Django 5.2.8 on 2026-06-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0101_add_booking_form_detail_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedGig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gig_id', models.IntegerField(db_index=True, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('date', models.DateField(db_index=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('address', models.TextField(blank=True, default='')),
                ('gig_status', models.CharField(db_index=True, max_length=50)),
                ('band', models.CharField(db_index=True, max_length=255)),
                ('raw_data', models.JSONField(default=dict)),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cached Gig',
                'verbose_name_plural': 'Cached Gigs',
                'ordering': ['date', 'time'],
                'indexes': [models.Index(fields=['date', 'gig_status', 'band'], name='blowcomotio_date_53fb5d_idx')],
            },
        ),
    ]
