# Generated by Django 6.0.6 on 2026-06-24 03:53

import modelcluster.fields

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0104_member_latest_revision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('serial_number', models.TextField(blank=True, help_text='Serial number or other identifying marks')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('available', 'Available'), ('needs_repair', 'Needs Repair'), ('disposed', 'Disposed')], default='available', max_length=50)),
                ('acquisition_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Original cost of acquiring this item', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, help_text='Current estimated value of this item', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('replacement_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated cost to replace this item', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, help_text='Additional context or maintenance notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage_location', models.ForeignKey(blank=True, help_text='Where this item is stored (leave blank if location is unknown)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='blowcomotion.instrumentstoragelocation')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('equipment', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='blowcomotion.equipment')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='blowcomotion.customimage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
