# Generated by Django 6.0.6 on 2026-06-24 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0104_member_latest_revision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('available', 'Available'), ('needs_repair', 'Needs Repair'), ('disposed', 'Disposed')], default='available', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('storage_location', models.ForeignKey(blank=True, help_text='Where this item is stored (leave blank if location is unknown)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='blowcomotion.instrumentstoragelocation')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'ordering': ['name'],
            },
        ),
    ]
