# Generated by Django 6.0.6 on 2026-06-25 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0105_add_equipment_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='allergens',
            field=models.JSONField(blank=True, default=list, help_text='List of allergens the member has'),
        ),
        migrations.AddField(
            model_name='member',
            name='allergens_other',
            field=models.TextField(blank=True, help_text='Other allergen details'),
        ),
        migrations.AddField(
            model_name='member',
            name='allergy_details',
            field=models.TextField(blank=True, help_text='Additional details about allergies or interventions'),
        ),
        migrations.AddField(
            model_name='member',
            name='dietary_other',
            field=models.TextField(blank=True, help_text='Other dietary preference details'),
        ),
        migrations.AddField(
            model_name='member',
            name='dietary_preferences',
            field=models.JSONField(blank=True, default=list, help_text='List of dietary preferences/practices'),
        ),
        migrations.AddField(
            model_name='member',
            name='has_allergies',
            field=models.BooleanField(blank=True, help_text='Does the member have food/substance allergies?', null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='has_epipen',
            field=models.BooleanField(blank=True, help_text='Does the member carry an Epi-Pen or other intervention?', null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='medical_notes',
            field=models.TextField(blank=True, help_text='CONFIDENTIAL: Any medical concerns or allergies (not shared outside admin)'),
        ),
        migrations.AddField(
            model_name='member',
            name='shirt_size',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL'), ('3XL', '3XL'), ('4XL', '4XL')], help_text='Adult unisex shirt size', max_length=10),
        ),
    ]
