# Generated by Django 6.0.6 on 2026-06-25 23:04

import wagtail.fields

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0106_member_allergens_member_allergens_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='instrument_rental_policy',
            field=wagtail.fields.RichTextField(blank=True, help_text='Lending policy text displayed on the instrument rental request form.'),
        ),
        migrations.CreateModel(
            name='InstrumentRentalRequestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('is_waitlist', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('policy_acknowledged', models.BooleanField(default=False)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_requests', to='blowcomotion.instrument')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_requests', to='blowcomotion.member')),
            ],
            options={
                'verbose_name': 'Instrument Rental Request',
                'verbose_name_plural': 'Instrument Rental Requests',
                'ordering': ['-date_submitted'],
            },
        ),
    ]
