# Generated by Django 6.0.6 on 2026-06-26 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0107_sitesettings_instrument_rental_policy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libraryinstrument',
            name='agreement_signed_date',
        ),
        migrations.AddField(
            model_name='instrument',
            name='hide_from_member_forms',
            field=models.BooleanField(default=False, help_text="Hide from member profile and signup instrument selectors. Use for instruments that members don't play but exist in inventory — e.g. a prop instrument or one not assigned to any section."),
        ),
        migrations.AddField(
            model_name='instrument',
            name='hide_from_rental',
            field=models.BooleanField(default=False, help_text='Hide from the instrument rental request form. Use for instruments too rare or unavailable to offer — e.g. a vintage sousaphone kept as a display piece.'),
        ),
        migrations.AddField(
            model_name='instrumentrentalrequestsubmission',
            name='admin_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='instrumentrentalrequestsubmission',
            name='assigned_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rental_assignments', to='blowcomotion.libraryinstrument'),
        ),
        migrations.AddField(
            model_name='instrumentrentalrequestsubmission',
            name='second_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rental_requests_second_choice', to='blowcomotion.instrument'),
        ),
        migrations.AddField(
            model_name='instrumentrentalrequestsubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='instrumentrentalrequestsubmission',
            name='third_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rental_requests_third_choice', to='blowcomotion.instrument'),
        ),
        migrations.DeleteModel(
            name='LibraryInstrumentDocument',
        ),
    ]
