# Generated by Django 6.0.6 on 2026-06-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0108_rental_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryinstrument',
            name='hide_from_member_forms',
            field=models.BooleanField(default=False, help_text='Hide this specific unit from member-facing instrument selectors. Use when a unit should not be visible to members but remains in admin inventory.'),
        ),
        migrations.AddField(
            model_name='libraryinstrument',
            name='hide_from_rental',
            field=models.BooleanField(default=False, help_text='Hide this specific unit from the rental request form. Use when a unit is damaged, reserved, or otherwise unavailable without removing it from inventory.'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='hide_from_member_forms',
            field=models.BooleanField(default=False, help_text="Hide this instrument type from member profile and signup instrument selectors. Use for instruments members don't play but exist in inventory — e.g. a prop instrument or one not assigned to any section."),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='hide_from_rental',
            field=models.BooleanField(default=False, help_text="Hide this instrument type from the rental request form. Use for instruments we carry but don't offer for general rental — e.g. a bass clarinet added to inventory because a member brought their own, but too rare to offer to others."),
        ),
    ]
