# Generated by Django 6.0.6 on 2026-06-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0109_library_instrument_hide_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrument',
            options={'verbose_name': 'Instrument Type', 'verbose_name_plural': 'Instrument Types'},
        ),
        migrations.AlterField(
            model_name='instrumentrentalrequestsubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('returned', 'Returned')], default='pending', max_length=20),
        ),
    ]
