# Generated by Django 6.0.6 on 2026-06-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0110_rental_returned_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentrentalrequestsubmission',
            name='patreon_validated',
            field=models.BooleanField(blank=True, help_text='Patreon membership confirmed active at submission time (null = not checked)', null=True),
        ),
    ]
