# Generated by Django 6.0.6 on 2026-06-27 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0111_rental_request_patreon_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentrentalrequestsubmission',
            name='patreon_validated',
            field=models.BooleanField(blank=True, help_text='Set automatically via Patreon API at submission time. Active = confirmed; Inactive = not found or inactive; Unknown = API not configured or check failed.', null=True),
        ),
    ]
