# Generated by Django 6.0.6 on 2026-06-27 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0112_alter_instrumentrentalrequestsubmission_patreon_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentrentalrequestsubmission',
            name='prior_storage_location',
            field=models.ForeignKey(blank=True, help_text='Storage location the instrument was in before being rented out. Restored on return.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blowcomotion.instrumentstoragelocation'),
        ),
    ]
