# Generated by Django 6.0.6 on 2026-06-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0113_instrumentrentalrequestsubmission_prior_storage_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='drive_file_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chart',
            name='drive_modified_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
