# Generated by Django 6.0.6 on 2026-06-27 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0113_instrumentrentalrequestsubmission_prior_storage_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryinstrument',
            name='last_nag_sent',
            field=models.DateField(blank=True, help_text='Date the most recent nag email was sent to this renter.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nag_cooldown_days',
            field=models.IntegerField(default=7, help_text='Days to wait before sending another nag email to the same renter.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='attendance_cleanup_days',
            field=models.IntegerField(default=90, help_text='Number of days since last seeing a member before they are marked inactive (attendance cleanup) and before instrument renters receive a nag email.'),
        ),
        migrations.CreateModel(
            name='InstrumentRentalNagLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=255)),
                ('member_email', models.EmailField(max_length=254)),
                ('reasons', models.CharField(help_text='Comma-separated trigger reasons: "attendance", "patreon", or "attendance+patreon"', max_length=255)),
                ('sent_at', models.DateField()),
                ('library_instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nag_logs', to='blowcomotion.libraryinstrument')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
