# Generated by Django 6.0.6 on 2026-06-29 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0115_chart_drive_pdf_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='drive_imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
