# Generated by Django 6.0.6 on 2026-07-01 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0116_add_chart_drive_imported_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentrentalrequestsubmission',
            name='patreon_last_charge_status',
            field=models.CharField(blank=True, help_text='Last Patreon charge status at time of check (e.g. Paid, Declined).', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='instrumentrentalrequestsubmission',
            name='patreon_lifetime_cents',
            field=models.PositiveIntegerField(blank=True, help_text='Lifetime Patreon support in cents at time of last check.', null=True),
        ),
        migrations.AddField(
            model_name='instrumentrentalrequestsubmission',
            name='patreon_patron_since',
            field=models.DateTimeField(blank=True, help_text='Date the member started their Patreon pledge.', null=True),
        ),
        migrations.AddField(
            model_name='instrumentrentalrequestsubmission',
            name='patreon_pledge_cents',
            field=models.PositiveIntegerField(blank=True, help_text='Monthly pledge amount in cents at time of last Patreon check.', null=True),
        ),
    ]
