# Generated by Django 6.0.6 on 2026-07-01 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0117_patreon_detail_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentrentalrequestsubmission',
            name='patreon_last_charge_date',
            field=models.DateTimeField(blank=True, help_text='Date of last Patreon charge attempt.', null=True),
        ),
    ]
