# Generated by Django 6.0.6 on 2026-07-01 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0114_nag_fields_and_log'),
        ('blowcomotion', '0118_patreon_last_charge_date'),
    ]

    operations = [
    ]
