# Generated by Django 6.0.6 on 2026-07-01 05:42

from django.db import migrations
from django.utils import timezone

BACKFILL_MARKER = "Backfilled from active rental by migration 0121_populate_active_rentals."


def populate_active_rentals(apps, schema_editor):
    """
    Create an InstrumentRentalRequestSubmission for every LibraryInstrument that is
    currently rented out but has no approved submission tracking it. These units
    predate (or were created outside of) the rental-requests dashboard, so they are
    invisible there even though they are actively rented.
    """
    import sys
    from datetime import datetime
    TESTING = 'test' in sys.argv

    LibraryInstrument = apps.get_model('blowcomotion', 'LibraryInstrument')
    InstrumentRentalRequestSubmission = apps.get_model('blowcomotion', 'InstrumentRentalRequestSubmission')

    STATUS_RENTED = 'rented'
    STATUS_APPROVED = 'approved'

    already_tracked_ids = set(
        InstrumentRentalRequestSubmission.objects.filter(
            status=STATUS_APPROVED,
        ).exclude(assigned_unit__isnull=True).values_list('assigned_unit_id', flat=True)
    )

    rented_units = (
        LibraryInstrument.objects.filter(status=STATUS_RENTED, member__isnull=False)
        .exclude(id__in=already_tracked_ids)
        .select_related('member', 'instrument')
    )

    created_count = 0
    for unit in rented_units:
        member = unit.member
        # apps.get_model() returns a historical model without the `full_name`
        # property, so replicate its logic (preferred_name if set, else first_name).
        full_name = f"{member.preferred_name} {member.last_name}" if member.preferred_name else f"{member.first_name} {member.last_name}"
        submission = InstrumentRentalRequestSubmission.objects.create(
            member=member,
            instrument=unit.instrument,
            name=full_name,
            email=member.email,
            phone=member.phone,
            address=member.address,
            status=STATUS_APPROVED,
            assigned_unit=unit,
            admin_message=BACKFILL_MARKER,
        )
        if unit.rental_date:
            # date_submitted is auto_now_add; overwrite it via update() so the
            # dashboard's "Submitted" date reflects the actual rental date.
            rental_datetime = timezone.make_aware(
                datetime.combine(unit.rental_date, datetime.min.time())
            )
            InstrumentRentalRequestSubmission.objects.filter(pk=submission.pk).update(
                date_submitted=rental_datetime,
            )
        created_count += 1

        if not TESTING:
            print(f"Backfilled rental request for {full_name} — {unit.instrument.name} (unit {unit.pk})")

    if not TESTING:
        print(f"\nMigration complete: created {created_count} rental request submission(s) for active rentals")


def reverse_migration(apps, schema_editor):
    """Delete only the submissions this migration created, identified by admin_message marker."""
    InstrumentRentalRequestSubmission = apps.get_model('blowcomotion', 'InstrumentRentalRequestSubmission')

    backfilled = InstrumentRentalRequestSubmission.objects.filter(admin_message=BACKFILL_MARKER)
    count = backfilled.count()
    backfilled.delete()

    print(f"Reversed migration: deleted {count} backfilled rental request submission(s)")


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0120_member_patreon_cache'),
    ]

    operations = [
        migrations.RunPython(populate_active_rentals, reverse_migration),
    ]
