# Generated by Django 6.0.6 on 2026-07-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blowcomotion", "0121_populate_active_rentals"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="weekly_birthday_summary_email_recipients",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated list of email addresses to receive weekly birthday update emails",
                max_length=1024,
                null=True,
            ),
        ),
    ]
