# Generated by Django 6.0.6 on 2026-07-02 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blowcomotion", "0121_populate_active_rentals"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SectionMember",
        ),
    ]
