# Generated by Django 6.0.6 on 2026-07-02 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0123_remove_section_member'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'permissions': [('access_dev_tools', 'Can access developer data dump tools'), ('access_real_data_exports', 'Can access real member data dumps and CSV exports')]},
        ),
    ]
