# Generated by Django 6.0.6 on 2026-07-03 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0124_alter_sitesettings_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='attendance_password',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='birthdays_password',
        ),
    ]
