# Generated by Django 6.0.6 on 2026-07-03 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0125_remove_sitesettings_attendance_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='is_conductor_chart',
            field=models.BooleanField(default=False, help_text='Check for conductor/full scores. When checked, instrument is not required.'),
        ),
        migrations.AlterField(
            model_name='chart',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blowcomotion.instrument'),
        ),
    ]
