# Generated by Django 6.0.6 on 2026-07-15 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0128_copy_member_fields_to_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'ordering': ['-date', 'member__user__last_name']},
        ),
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='last_name',
        ),
    ]
