# Generated by Django 6.0.6 on 2026-07-16 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0129_alter_attendancerecord_options_remove_member_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='invite_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the set-password invite email was last sent by invite_members', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
    ]
