# Generated by Django 6.0.6 on 2026-07-15 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0130_member_invite_sent_at_alter_member_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminToolUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(help_text='Identifier for the admin tool/page, e.g. its path.', max_length=255)),
                ('action', models.CharField(blank=True, help_text='What was done, e.g. the id/label of the button clicked. Blank for a plain page view.', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_tool_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Tool Usage',
                'verbose_name_plural': 'Admin Tool Usage Records',
                'indexes': [models.Index(fields=['timestamp'], name='blowcomotio_timesta_46252d_idx')],
            },
        ),
    ]
