# Generated by Django 6.0.6 on 2026-08-16 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blowcomotion', '0134_alter_blankcanvaspage_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='member',
            field=models.ForeignKey(blank=True, help_text='Member currently holding this item (leave blank if stored in a storage location)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_equipment', to='blowcomotion.member'),
        ),
    ]
