# Generated by Django 6.0.6 on 2026-07-05 06:01

import modelcluster.fields

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blowcomotion', '0125_remove_sitesettings_attendance_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('close_time', models.DateTimeField(help_text='When bidding closes. Individual items may run longer if soft close extends them.')),
                ('soft_close_enabled', models.BooleanField(default=False, help_text="Anti-sniping: a bid placed in the final minutes pushes that item's deadline out by the same window, so auctions end when bidding truly stops.")),
                ('soft_close_minutes', models.PositiveIntegerField(default=5)),
                ('payment_instructions', models.TextField(blank=True, help_text='Included in winner notifications (where/how to pay and pick up).')),
                ('summary_sent_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuctionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, help_text='Item number used on printed cards and in SMS bids (auto-assigned if blank).', null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('starting_bid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bid_increment', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('close_time', models.DateTimeField(blank=True, help_text="Leave blank to use the auction's close time.", null=True)),
                ('winner_notified_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='auction.auction')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='AuctionItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='blowcomotion.customimage')),
                ('item', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='auction.auctionitem')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('source', models.CharField(choices=[('web', 'Web'), ('sms', 'SMS')], default='web', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auction.auctionitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='backup_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auction.bid'),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='winning_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auction.bid'),
        ),
        migrations.CreateModel(
            name='Bidder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('sms_opt_in', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidders', to='auction.auction')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_bidders', to='blowcomotion.member')),
            ],
        ),
        migrations.AddField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auction.bidder'),
        ),
        migrations.AddConstraint(
            model_name='auctionitem',
            constraint=models.UniqueConstraint(fields=('auction', 'number'), name='unique_item_number_per_auction'),
        ),
        migrations.AddConstraint(
            model_name='bidder',
            constraint=models.UniqueConstraint(fields=('auction', 'phone'), name='unique_bidder_phone_per_auction'),
        ),
        migrations.AddConstraint(
            model_name='bidder',
            constraint=models.UniqueConstraint(fields=('auction', 'email'), name='unique_bidder_email_per_auction'),
        ),
        migrations.AddConstraint(
            model_name='bidder',
            constraint=models.UniqueConstraint(condition=models.Q(('member__isnull', False)), fields=('auction', 'member'), name='unique_bidder_member_per_auction'),
        ),
    ]
