# Generated by Django 6.0.7 on 2026-09-30 03:14

import wagtail.fields

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='user_agreement',
            field=wagtail.fields.RichTextField(blank=True, help_text='Shown to new bidders, who must accept it before their first bid. Leave blank to skip.'),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='buy_now_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional. A bid at this amount wins the item immediately. Leave blank for no Buy It Now.', max_digits=8, null=True),
        ),
    ]
